#ifndef HERBARY_STD_DEFINE__STATIC_ASSERT_H_INCLUDED_BOOL
#define HERBARY_STD_DEFINE__STATIC_ASSERT_H_INCLUDED_BOOL 0
#elif HERBARY_STD_DEFINE__STATIC_ASSERT_H_INCLUDED_BOOL != 0 \
        && HERBARY_STD_DEFINE__STATIC_ASSERT_H_INCLUDED_BOOL != 1
#error "`HERBARY_STD_DEFINE__STATIC_ASSERT_H_INCLUDED_BOOL` must be in range of [0; 1]"
#endif // HERBARY_STD_DEFINE__STATIC_ASSERT_H_INCLUDED_BOOL
